<a href="https://colab.research.google.com/github/Spal18/Python/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Theory Questions***

In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
#Numpy-Numerical python-As a python library
#Numpy data is stored as a form of array- Array stores homogeneous data in continous memory location- Which makes it faster
#Numpy Computation is very fast-It is built using C(fastest programming language)
#NumPy can handle advanced mathematical operations like matrix multiplication
#NumPy enhances Python's role in data science by providing efficient multidimensional arrays for mathematical operations.

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
#np.mean()- Use to calculate arithmetic mean- All elements have equal weight/axis- Weight cannot be passed trough the parameter of the given function.

import numpy as np
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

#np.average()- Use to calculate arithmetic mean with weighted average- All elements may or may not have equal weight- Weight can be passed through the parameter of the given function.

import numpy as np
arr = np.array([1,2,3,4,5])
wei = np.array([5,10,2,3,9])
print(np.average(arr,weights=wei))


3.0
3.0344827586206895


In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
#Ans. 1D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
res = np.flip(arr)
print(res)

# 2D arrays
arr1 = np.array(([1,2,3,4],[5,6,7,8]))
res1 = np.flip(arr1)
print(res1)


[8 7 6 5 4 3 2 1]
[[8 7 6 5]
 [4 3 2 1]]


In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
#Ans. In NumPy, we can determine the data type of elements in a NumPy array using the dtype attribute.
#NumPy offers several data types, including  integer types, floating-point types, and complex number types
#they help ensure that programs use memory efficiently and perform correctly by Memory allocation, Code reliability, Program accuracy, Program speed
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(arr.dtype)

arr1 = np.array([1.5,2.5,3.6,2.8])
print(arr1.dtype)


int64
float64


In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
"""Ans.Key Features of NumPy ndarrays:
#1.Homogeneous Data Type: All elements in an ndarray must have the same data type.
#2. N-Dimensional:ndarrays can have multiple dimension.
#3.Efficient Operations: NumPy supports vectorized operations, which means operations are applied element-wise, leading to faster execution compared to loops in standard Python lists.
#4.Broadcasting:This feature allows NumPy to perform operations on arrays of different shapes by automatically expanding them to a common shape.
#5.Memory Efficiency: ndarrays are stored in contiguous blocks of memory, which enhances performance for large datasets.
#6.Rich Functionality: NumPy provides numerous functions for array creation, manipulation, and mathematical operations, such as np.zeros, np.ones, np.full, np.empty, np.arange, and np.linspace.

#Differences from Standard Python Lists:
#1.Data Type Consistency: Python lists can contain elements of different data types, whereas ndarrays require all elements to be of the same type.
#2.Performance: ndarrays are generally faster and more memory-efficient than Python lists, especially for large datasets and numerical operations.
#3.Dimensionality: While Python lists can be nested to create multi-dimensional structures, ndarrays are inherently multi-dimensional and provide more efficient and intuitive ways to handle such data.
#4.Functionality: NumPy offers a wide range of built-in functions for mathematical and statistical operations, which are not available for standard Python lists."""


In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
#Ans.NumPy arrays offer several performance benefits over Python lists, especially for large-scale numerical operations.
#like: Memory Efficiency,Speed,Functionality,Multidimensional data,widely supported and compatible.
"Creating array object"
arr = np.array([[1, 2, 3],
                [4, 2, 5]])

print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Array stores elements of type:  int64


In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
# Ans.vstack()
#Purpose: Stacks arrays vertically (row-wise).
#Usage:Useful when you want to add rows to an existing array.
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.vstack((a,b))
print(np.vstack((a,b)))

#hstack()
#Purpose:Stacks arrays horizontally (column-wise).
#Usage: Useful when you want to add columns to an existing array.
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.hstack((a,b))
print(np.hstack((a,b)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimension.
#Ans. fliplr()
#Function: Flips the array left to right.
#Axis: Operates along axis 1 (horizontal axis).
#Effect on 2D Arrays: Reverses the order of columns while keeping the rows intact.
a=np.array([[1,2,3],[4,5,6]])
np.fliplr(a)
print(np.fliplr(a))
# flipud()
#Function: Flips the array up-down.
#Axis: Operates along axis 0 (vertical axis).
#Effect on 2D Arrays: Reverses the order of rows while keeping the columns intact.
a=np.array([[1,2,3],[4,5,6]])
np.flipud(a)
print(np.flipud(a))


[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#Ans.The array_split() method in NumPy is used to split an array into multiple sub-arrays. This function is particularly useful when you need to divide an array into parts that may not be of equal size.
#Functionality
#ary: The input array to be split.
#indices_or_sections: If an integer, it indicates the number of equal or nearly equal sub-arrays to be created. If a list of sorted integers, it specifies the points at which the array is split.
#axis: The axis along which to split the array. The default is 0 (along rows).

#Handling Uneven Splits
#When the array cannot be evenly divided by the specified number of splits, array_split() ensures that the resulting sub-arrays are as equal in size as possible. For example, if you have an array of length 9 and you want to split it into 4 parts, array_split() will create sub-arrays of sizes 3, 2, 2, and 2.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

result = np.array_split(arr, 4)

print(result)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''Numpy arrays are homogeneous in nature means it is an array that contains data of a single type only.
-Through vectorization and Broadcasting,we can perform mathematical operations on arrays of different shapes/dimensions.
--Broadcasting for expand a smaller shape array and vectorization is for fastest calculations.
--The concept of vectorized operations on NumPy allows the use of more optimal and pre-compiled functions and mathematical operations on NumPy array objects and data sequences.
-The Output and Operations will speed up when compared to simple non-vectorized operations.'''
#Python’s lists and tuples are unrestricted in the type of data they contain.


# ***Practical Questions***

In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
# 3x3 Numpy array
Arr = np.random.randint(1,100,(3,3))
print(Arr)

Arr1 = np.roll(Arr, 2)
print(Arr1)


[[55 98 63]
 [73 61 59]
 [11  3 79]]
[[ 3 79 55]
 [98 63 73]
 [61 59 11]]


In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

arr1 = np.reshape(arr,(2,5))
print(arr1)

arr2 = np.reshape(arr1,(5,2))
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
#Ans. 4x4 Numpy array
Ar = np.random.rand(4,4)
print(Ar)

#border of Zeros
Ar1 = np.pad(Ar,1)
print(Ar1)

#Shape of resulting array(Ar1)
print("Shape of array -", Ar1.shape)

[[0.24292627 0.39067649 0.32669195 0.82819674]
 [0.79367788 0.81025886 0.91741621 0.71869922]
 [0.17867121 0.5227685  0.87050506 0.17859079]
 [0.22137857 0.57706059 0.82079876 0.53643411]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.24292627 0.39067649 0.32669195 0.82819674 0.        ]
 [0.         0.79367788 0.81025886 0.91741621 0.71869922 0.        ]
 [0.         0.17867121 0.5227685  0.87050506 0.17859079 0.        ]
 [0.         0.22137857 0.57706059 0.82079876 0.53643411 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
Shape of array - (6, 6)


In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
#Ans. array between 10 & 60
Array = np.arange(10,60,(5))
Array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
# Creating a NumPy array containing strings
Arr = np.array(['Python', 'Numpy','Pandas'])
print("Main Array:",Arr)

# Converting all characters to lowercase
lowered_case = np.char.lower(Arr)
print("Lowered: ", lowered_case)

# Converting all characters to uppercase
uppered_case = np.char.upper(Arr)
print("Uppered: ", uppered_case)

# Swapping the case of characters (lowercase to uppercase and vice versa)
swapcased_case = np.char.swapcase(Arr)
print("Swapcased: ", swapcased_case)

# Capitalizing the first character of each word in the string
titlecased_case = np.char.title(Arr)
print("Titlecased: ", titlecased_case)


Main Array: ['Python' 'Numpy' 'Pandas']
Lowered:  ['python' 'numpy' 'pandas']
Uppered:  ['PYTHON' 'NUMPY' 'PANDAS']
Swapcased:  ['pYTHON' 'nUMPY' 'pANDAS']
Titlecased:  ['Python' 'Numpy' 'Pandas']


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
#Array of words >> String array
Arr = np.array(['Python','Numpy','Pandas',"Seaborn","Plotly"])
print(Arr)

#to insert space in words
Arr11 = np.char.join(" ", Arr)
print(Arr11)

['Python' 'Numpy' 'Pandas' 'Seaborn' 'Plotly']
['P y t h o n' 'N u m p y' 'P a n d a s' 'S e a b o r n' 'P l o t l y']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
X = np.random.randint(1,5,(3,3))
Y = np.random.randint(1,5,(3,3))
print("X:",X)
print("Y:",Y)

#addition
A = np.add(X,Y)
print("Add:",A)

#subtraction
B = np.subtract(X,Y)
print("Subtract:",B)

#multiplication
C = np.multiply(X,Y)
print("Multiply:",C)

#Division
D = np.divide(X,Y)
print("Divide:",D)

X: [[4 3 2]
 [2 1 4]
 [4 3 1]]
Y: [[4 2 3]
 [1 3 4]
 [4 2 1]]
Add: [[8 5 5]
 [3 4 8]
 [8 5 2]]
Subtract: [[ 0  1 -1]
 [ 1 -2  0]
 [ 0  1  0]]
Multiply: [[16  6  6]
 [ 2  3 16]
 [16  6  1]]
Divide: [[1.         1.5        0.66666667]
 [2.         0.33333333 1.        ]
 [1.         1.5        1.        ]]


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
# Creating a diagonal matrix with diagonal elements 1, 2, 3, 4, 5 using np.diag()
Mat = np.diag([1, 2, 3, 4, 5])

# Printing the diagonal matrix 'x'
print(Mat)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array
import numpy as np
import math
A = np.random.randint(0,1000,(10,10))
print("Main array:",A)
def is_prime(n):
    if n % 2 == 0 and n > 2:
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))
B = np.vectorize(is_prime)
C = B(A)
primes = np.extract(C, A)
primes

Main array: [[820 306 436  32 846  73 963 615 458 512]
 [582 893 466 439 152 548 811  27 115 454]
 [630  65 138 346 661 241 711  50 154 623]
 [ 18  97 268 946 456 494 109 654  13 658]
 [719 526 281 291 237 759 243  78 533 851]
 [654 312 162 833 988 716 818 449 954  81]
 [291 349 204  45  46 734 833 150 805 122]
 [626  94  75 854   3 132 268 950 146 311]
 [791 715 955 140 664 797 494 147 468 956]
 [146 393 924  20 387 346 987 446 913 954]]


array([ 73, 439, 811, 661, 241,  97, 109,  13, 719, 281, 449, 349,   3,
       311, 797])

In [1]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

#30 days temperature array
temperatures = np.array([29, 29, 30, 27, 28, 29, 30, 31, 29, 28, 27, 26, 25, 24, 23, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 31, 30, 29, 28])

# Reshape the array into a 2D array with rows representing weeks (assuming 5 weeks)
weekly_temps = temperatures.reshape(5, 6)

# Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temps, axis=1)

# Display the weekly averages
print("Weekly Average Temperatures:")
for i, avg in enumerate(weekly_averages):
  print(f"Week {i+1}: {avg:.2f}")

Weekly Average Temperatures:
Week 1: 28.67
Week 2: 28.50
Week 3: 23.50
Week 4: 27.50
Week 5: 30.17
